### ISSUE TITLE
Adding routes

### ISSUE THREAD

**Issue by coen-hyde** [TryGhost/Ghost-App#20]
I've looked and I can't find a way to add a route through an app. Is this currently possible?

**Comment by ErisDS** [comment]
The App framework is in it's very, very early stages, so I'm afraid it's not possible yet. 

Everything that is possible is listed here: https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs these docs are aimed at developers building the platform because it's still in such early development ;)
